server:
  port: 8000
  servlet:
    encoding:
      charset: utf-8

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/minidb
    driver-class-name: org.mariadb.jdbc.Driver
    username: miniproject2
    password: 12345678!

  output:
    ansi:
      enabled: always

logging:
  level:
    '[org.hibernate.SQL]': DEBUG
    '[site.metacoding.miniproject2]': DEBUG